name: 2.1 Hello
on:
  workflow_dispatch
    inputs:
      gretting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.gretting}}"
